/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.eaut_app.ui;

import com.mycompany.eaut_app.dao.BangDiemDao;
import com.mycompany.eaut_app.dao.SinhVienDao;
import com.mycompany.eaut_app.helpers.DataValidator;
import com.mycompany.eaut_app.helpers.MessageDialogHelper;
import com.mycompany.eaut_app.model.BangDiem;
import com.mycompany.eaut_app.model.SinhVien;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author trieuquangsang
 */
public class Thongke_panel extends javax.swing.JPanel {

    private MainForm parentForm;
    private  DefaultTableModel tblModel ;

    /**
     * Creates new form Thongke_panel
     */
    public Thongke_panel() {
        initComponents();
        
        initTable();
        loadBangDiem();
        
    }
    
    /*
    public void runText(){
        final int Max_X = 450 ;
        final int Min_x = 50 ;
        Thread animation = new Thread(new Runnable() {
            @Override
            public void run() {
               int x = 5;
               int y = 5 ;
                while (true) {  
                    title_run.setLocation(x, y);
                    x += 10 ;
                    try {
                        Thread.sleep(200);
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }
            }
        });
        animation.start();
    }
    
  */  
    private void  initTable(){
        tblModel = new DefaultTableModel();
        tblModel.setColumnIdentifiers(new  String[]{
                "Mã Sinh Viên", "Tiếng Anh", "Lập Trình HĐT", "GDTC", "Điểm TB"
            } );
        
        tbl_data.setModel(tblModel);
    
    }
    
    private void loadBangDiem(){
        try {
            BangDiemDao dao = new BangDiemDao();
            List<BangDiem> list = dao.findTop(5);
            tblModel.setRowCount(0);
            for (BangDiem bd : list) {
                tblModel.addRow(new Object[]
                {
                    bd.getMaSV() , bd.getTiengAnh(), bd.getLTHDT() , bd.getGDTC() ,
                    (bd.getTiengAnh()+ bd.getLTHDT()+ bd.getGDTC())/3
                });
            }
               tblModel.fireTableDataChanged();
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(parentForm, e.getMessage(), "Lỗi");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        title_run = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        seach_masv = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_masv = new javax.swing.JTextField();
        txt_hoten = new javax.swing.JTextField();
        txt_tienganh = new javax.swing.JTextField();
        txt_java = new javax.swing.JTextField();
        txt_thechat = new javax.swing.JTextField();
        btn_seach = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        diem = new javax.swing.JLabel();
        btn_new = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_data = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(204, 204, 255));

        title_run.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        title_run.setForeground(new java.awt.Color(255, 0, 0));
        title_run.setText("Thống Kê Điểm");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Mã Sinh Viên :");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Mã Sinh Viên :");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Họ Tên :");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Tiếng Anh :");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Lập Trình HĐT:");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Giáo Dục Thể Chất :");

        txt_masv.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_masvFocusLost(evt);
            }
        });
        txt_masv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_masvActionPerformed(evt);
            }
        });

        txt_tienganh.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_tienganhFocusLost(evt);
            }
        });

        txt_java.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_tienganhFocusLost(evt);
            }
        });
        txt_java.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_javaActionPerformed(evt);
            }
        });

        txt_thechat.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_tienganhFocusLost(evt);
            }
        });

        btn_seach.setBackground(new java.awt.Color(255, 255, 51));
        btn_seach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/eaut_app/icons/search-icon-16.png"))); // NOI18N
        btn_seach.setText("TÌm Kiếm");
        btn_seach.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_seach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_seachActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("Điểm TB");

        diem.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        diem.setText("9.5");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(diem)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(diem)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        btn_new.setBackground(new java.awt.Color(255, 255, 51));
        btn_new.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btn_new.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/eaut_app/icons/new-icon-16.png"))); // NOI18N
        btn_new.setText("Nhập Mới ");
        btn_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_newActionPerformed(evt);
            }
        });

        btn_save.setBackground(new java.awt.Color(255, 255, 51));
        btn_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/eaut_app/icons/Save-icon.png"))); // NOI18N
        btn_save.setText("Lưu");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        btn_update.setBackground(new java.awt.Color(255, 255, 51));
        btn_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/eaut_app/icons/Actions-document-edit-icon-16.png"))); // NOI18N
        btn_update.setText("Cập Nhật ");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_delete.setBackground(new java.awt.Color(255, 255, 51));
        btn_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/eaut_app/icons/Actions-edit-delete-icon-16.png"))); // NOI18N
        btn_delete.setText("Xóa");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        tbl_data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_data);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/eaut_app/icons/Logo_eaut.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_masv)
                    .addComponent(txt_hoten)
                    .addComponent(txt_tienganh)
                    .addComponent(txt_java)
                    .addComponent(txt_thechat, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btn_new, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_save, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_delete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 225, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(135, 135, 135))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(168, 168, 168))))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(270, 270, 270)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(seach_masv, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(btn_seach, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(331, 331, 331)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addComponent(jSeparator2))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(436, 436, 436)
                .addComponent(title_run)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(title_run)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(seach_masv, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_seach, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(txt_masv, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn_new)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_save)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_update)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_delete))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(txt_hoten, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel4))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(txt_tienganh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel5))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(txt_java, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel6)))
                                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txt_thechat, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7)))))
                            .addComponent(jLabel11))
                        .addGap(26, 26, 26)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_javaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_javaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_javaActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        btn_saveActionPerformed(evt);
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        StringBuilder sb = new StringBuilder();
        DataValidator.validateEmpty(txt_masv, sb, "Vui lòng nhập mã sinh viên !");
        DataValidator.validateEmpty(txt_tienganh, sb, "Vui lòng nhập điểm sinh viên !");
        DataValidator.validateEmpty(txt_java, sb, "");
        DataValidator.validateEmpty(txt_thechat, sb, "");
        if (sb.length() > 0) {
            MessageDialogHelper.showErrorDialog(parentForm, sb.toString(), "Lỗi");
            return;
        }
        try {
            BangDiem bd = new BangDiem();
            bd.setMaSV(txt_masv.getText());
            bd.setTiengAnh(Float.parseFloat(txt_tienganh.getText()));
            bd.setLTHDT(Float.parseFloat(txt_java.getText()));
            bd.setGDTC(Float.parseFloat(txt_thechat.getText()));

            BangDiemDao dao = new BangDiemDao();
            if (dao.findByMaSv(txt_masv.getText()) != null) {
                if(MessageDialogHelper.showConfirmDialog(parentForm
                        , "Bạn có muốn cập nhật điểm không ", "Thông báo")== JOptionPane.NO_OPTION){
                    return;
                }
                if (dao.update(bd)) {
                    MessageDialogHelper.showMessageDialog(parentForm, "Bảng điểm đã cập nhật ", "Thông báo !");
                } else {
                    MessageDialogHelper.showMessageDialog(parentForm, "Không thể cập nhật", "Thông báo !");
                }
            } else {
                if (dao.insert(bd)) {
                    MessageDialogHelper.showMessageDialog(parentForm, "Bảng điểm đã được lưu ", "Thông báo !");
                } else {
                    MessageDialogHelper.showMessageDialog(parentForm, "Không thể lưu điểm", "Thông báo !");
                }
            }
            
            loadBangDiem();
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(parentForm, e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_btn_saveActionPerformed

    private void btn_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_newActionPerformed
        txt_hoten.setText("");
        txt_masv.setText("");
        txt_thechat.setText("");
        txt_tienganh.setText("");
        txt_java.setText("");
    }//GEN-LAST:event_btn_newActionPerformed

    private void txt_masvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_masvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_masvActionPerformed

    private void txt_masvFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_masvFocusLost
        try {
            SinhVienDao dao = new SinhVienDao();
            SinhVien sv = dao.findByid(txt_masv.getText());
            if (sv !=null) {
                txt_hoten.setText(sv.getHoTen());
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
            
    }//GEN-LAST:event_txt_masvFocusLost

    private void txt_tienganhFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_tienganhFocusLost
        if (txt_tienganh.getText().equals("") ||
                txt_java.getText().equals("")||
                txt_thechat.getText().equals("")   ) {
            return;
        }
        
        float ta = Float.parseFloat(txt_tienganh.getText());
        float LTHDT = Float.parseFloat(txt_java.getText());
        float GDTC = Float.parseFloat(txt_thechat.getText());
        
        float avg = (ta + LTHDT + GDTC)/3 ;
        
        String st = String.format("%.2f", avg);
        diem.setText(st);
    }//GEN-LAST:event_txt_tienganhFocusLost

    private void btn_seachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_seachActionPerformed
        try {
            BangDiemDao dao = new BangDiemDao();
            BangDiem bd = dao.findByMaSv(seach_masv.getText());
            
            if (bd != null) {
               txt_masv.setText(bd.getMaSV());
               txt_tienganh.setText(String.format("%.2f", bd.getTiengAnh()));
               txt_java.setText(String.format("%.2f", bd.getLTHDT()));
               txt_thechat.setText(String.format("%.2f", bd.getGDTC()));
               
                txt_masvFocusLost(null);
                txt_tienganhFocusLost(null);
            }else{
                MessageDialogHelper.showMessageDialog(parentForm, "Không tìm thấy mã sinh viên theo yêu cầu", "Thông báo !");
            }
            
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(parentForm, e.getMessage(), "Lỗi");
        }
            
    }//GEN-LAST:event_btn_seachActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        try {
            if (txt_masv.getText().equals("")) {
                MessageDialogHelper.showMessageDialog(parentForm, "Cần phải nhập mã sinh viên", "Thông báo");
            }
            
            BangDiemDao dao = new BangDiemDao();
            BangDiem bd = dao.findByMaSv(txt_masv.getText());
            if (bd ==null) {
                MessageDialogHelper.showMessageDialog(parentForm, "Mã sinh viên không tồn tại", "Thông báo");
                return;
            }
            if(MessageDialogHelper.showConfirmDialog(parentForm, "Bạn có muốn xóa sinh viên không ?", "Thông báo")
                    == JOptionPane.NO_OPTION){
                    return;
             }
            if (dao.deleteByMaSv(txt_masv.getText())) {
                MessageDialogHelper.showMessageDialog(parentForm, "Điểm của sinh viên đã xóa thành công", "Thông báo");
            }else{
                MessageDialogHelper.showMessageDialog(parentForm, "Điểm của sinh viên xóa không thành công", "Thông báo");
            }
            loadBangDiem();
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(parentForm, e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_btn_deleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_new;
    private javax.swing.JButton btn_save;
    private javax.swing.JButton btn_seach;
    private javax.swing.JButton btn_update;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel diem;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField seach_masv;
    private javax.swing.JTable tbl_data;
    private javax.swing.JLabel title_run;
    private javax.swing.JTextField txt_hoten;
    private javax.swing.JTextField txt_java;
    private javax.swing.JTextField txt_masv;
    private javax.swing.JTextField txt_thechat;
    private javax.swing.JTextField txt_tienganh;
    // End of variables declaration//GEN-END:variables
}
